import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aloha | A Library of Helpful Articles!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         A Library of Helpful Articles!
        </h1>

        <p className={styles.description}>
          Discover helpful articles that can help you develop your craft
        </p>

      </main>

      <footer className={styles.footer}>
        <ul>
          <li>Home</li>
          <li>About</li>
        </ul>
      </footer>
    </div>
  )
}

export default Home
